// paths to API resources
import {API_BASE_URL} from "@/utils/constants"

export var password_reset_resource = `http://${API_BASE_URL}/reset/`;
export var email_confirm_resource = `http://${API_BASE_URL}/confirm/`;
export var quantity_type_resource = `http://${API_BASE_URL}/quantity-type`;
export var redcap_sample_resource = `http://${API_BASE_URL}/redcap-samples`;
export var request_password_reset_resource = `http://${API_BASE_URL}/forgot`;
export var bio_hazard_level_resource = `http://${API_BASE_URL}/bio-hazard-level`;
export var request_confirm_resource = `http://${API_BASE_URL}/requestConfirmation`;
export var box_resource = `http://${API_BASE_URL}/box`;
export var slot_resource = `http://${API_BASE_URL}/slot`;
export var rack_resource = `http://${API_BASE_URL}/rack`;
export var tray_resource = `http://${API_BASE_URL}/tray`;
export var role_resource = `http://${API_BASE_URL}/role`;
export var user_resource = `http://${API_BASE_URL}/user`;
export var theme_resource = `http://${API_BASE_URL}/theme`;
export var lab_resource = `http://${API_BASE_URL}/lab`;
export var sample_resource = `http://${API_BASE_URL}/sample`;
export var project_resource = `http://${API_BASE_URL}/project`;
export var freezer_resource = `http://${API_BASE_URL}/freezer`;
export var chamber_resource = `http://${API_BASE_URL}/chamber`;
export var logout_resource = `http://${API_BASE_URL}/logout`;
export var publication_resource = `http://${API_BASE_URL}/publication`;
export var sample_request_resource = `http://${API_BASE_URL}/request-sample`;
export var auth_resource = `http://${API_BASE_URL}/auth`;
export var sample_response_resource = `http://${API_BASE_URL}/request-response/`;
export var study_block_resource = `http://${API_BASE_URL}/study-block/`;
export var house_hold_data_resource = `http://${API_BASE_URL}/house-data/`;
