"""Changed Columns in Sample Model to be nullable

Revision ID: 02886a4afc2c
Revises: 555a9ef3bb55
Create Date: 2019-12-11 16:33:09.850347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02886a4afc2c'
down_revision = '555a9ef3bb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'animal_species',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'animal_species',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
