"""Changed Columns in Sample Model to be nullable

Revision ID: 02886a4afc2c
Revises: 555a9ef3bb55
Create Date: 2019-12-11 16:33:09.850347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02886a4afc2c'
down_revision = '555a9ef3bb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sampletest')
    op.alter_column('sample', 'animal_species',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'animal_species',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('sampletest',
    sa.Column('freezer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chamber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tray', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('box', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('box_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
