"""Added Code to Laboratory Model

Revision ID: 04007c59f87a
Revises: 798bc25aae47
Create Date: 2019-11-25 13:00:40.300895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04007c59f87a'
down_revision = '798bc25aae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory', sa.Column('code', sa.String(length=65), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('laboratory', 'code')
    # ### end Alembic commands ###
