"""Made code in samples unique and not null

Revision ID: 06570f5559c8
Revises: 5801c9720bb1
Create Date: 2020-02-14 11:57:48.570250

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '06570f5559c8'
down_revision = '5801c9720bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_unique_constraint(None, 'sample', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='unique')
    op.alter_column('sample', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
