"""Unique code of role dropped

Revision ID: 0f0da4cce4ea
Revises: 6fcc5ad48cca
Create Date: 2021-01-27 10:13:23.792990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0da4cce4ea'
down_revision = '6fcc5ad48cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_index('ix_role_code', table_name='role')
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.create_index('ix_role_code', 'role', ['code'], unique=True)
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
