"""Modified user model to add restrictions on fields.

Revision ID: 0fa389b1067f
Revises: 54af49545db8
Create Date: 2019-11-13 13:17:19.175727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa389b1067f'
down_revision = '54af49545db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=65), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=65), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
