"""Retention period db field changed to datetime

Revision ID: 12ddc471a96d
Revises: 96a40efa632d
Create Date: 2020-04-22 13:32:18.285086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12ddc471a96d'
down_revision = '96a40efa632d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('retention_date', sa.DateTime(), nullable=True))
    op.drop_column('sample', 'retention_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('retention_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sample', 'retention_date')
    # ### end Alembic commands ###
