"""Added fields in Sample Model and onDelete method on all Foreign Keys

Revision ID: 177c317004ab
Revises: 4e51c3141240
Create Date: 2019-12-02 12:41:16.023525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177c317004ab'
down_revision = '4e51c3141240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('box_tray_id_fkey', 'box', type_='foreignkey')
    op.create_foreign_key(None, 'box', 'tray', ['tray_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('chamber_freezer_id_fkey', 'chamber', type_='foreignkey')
    op.create_foreign_key(None, 'chamber', 'freezer', ['freezer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('freezer_laboratory_id_fkey', 'freezer', type_='foreignkey')
    op.create_foreign_key(None, 'freezer', 'laboratory', ['laboratory_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('publication_sample_id_fkey', 'publication', type_='foreignkey')
    op.create_foreign_key(None, 'publication', 'sample', ['sample_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('rack_chamber_id_fkey', 'rack', type_='foreignkey')
    op.create_foreign_key(None, 'rack', 'chamber', ['chamber_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('sample_box_id_fkey', 'sample', type_='foreignkey')
    op.drop_constraint('sample_user_id_fkey', 'sample', type_='foreignkey')
    op.drop_constraint('sample_theme_id_fkey', 'sample', type_='foreignkey')
    op.create_foreign_key(None, 'sample', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sample', 'box', ['box_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sample', 'theme', ['theme_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tray_rack_id_fkey', 'tray', type_='foreignkey')
    op.create_foreign_key(None, 'tray', 'rack', ['rack_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'role', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'tray', type_='foreignkey')
    op.create_foreign_key('tray_rack_id_fkey', 'tray', 'rack', ['rack_id'], ['id'])
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.create_foreign_key('sample_theme_id_fkey', 'sample', 'theme', ['theme_id'], ['id'])
    op.create_foreign_key('sample_user_id_fkey', 'sample', 'users', ['user_id'], ['id'])
    op.create_foreign_key('sample_box_id_fkey', 'sample', 'box', ['box_id'], ['id'])
    op.drop_constraint(None, 'rack', type_='foreignkey')
    op.create_foreign_key('rack_chamber_id_fkey', 'rack', 'chamber', ['chamber_id'], ['id'])
    op.drop_constraint(None, 'publication', type_='foreignkey')
    op.create_foreign_key('publication_sample_id_fkey', 'publication', 'sample', ['sample_id'], ['id'])
    op.drop_constraint(None, 'freezer', type_='foreignkey')
    op.create_foreign_key('freezer_laboratory_id_fkey', 'freezer', 'laboratory', ['laboratory_id'], ['id'])
    op.drop_constraint(None, 'chamber', type_='foreignkey')
    op.create_foreign_key('chamber_freezer_id_fkey', 'chamber', 'freezer', ['freezer_id'], ['id'])
    op.drop_constraint(None, 'box', type_='foreignkey')
    op.create_foreign_key('box_tray_id_fkey', 'box', 'tray', ['tray_id'], ['id'])
    # ### end Alembic commands ###
