"""Cascade delete for all resources dependent on freezer.

Revision ID: 18d9a31dd9ce
Revises: e4d413c34c1b
Create Date: 2020-12-15 16:26:18.677065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d9a31dd9ce'
down_revision = 'e4d413c34c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chamber_freezer_id_fkey', 'chamber', type_='foreignkey')
    op.create_foreign_key(None, 'chamber', 'freezer', ['freezer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rack_chamber_id_fkey', 'rack', type_='foreignkey')
    op.create_foreign_key(None, 'rack', 'chamber', ['chamber_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tray_rack_id_fkey', 'tray', type_='foreignkey')
    op.create_foreign_key(None, 'tray', 'rack', ['rack_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tray', type_='foreignkey')
    op.create_foreign_key('tray_rack_id_fkey', 'tray', 'rack', ['rack_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'rack', type_='foreignkey')
    op.create_foreign_key('rack_chamber_id_fkey', 'rack', 'chamber', ['chamber_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'chamber', type_='foreignkey')
    op.create_foreign_key('chamber_freezer_id_fkey', 'chamber', 'freezer', ['freezer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
