"""Added fields for project

Revision ID: 192f2be30501
Revises: d8f73aff3e67
Create Date: 2020-05-12 11:23:17.409427

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '192f2be30501'
down_revision = 'd8f73aff3e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('head', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_foreign_key(None, 'project', 'users', ['head'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_column('project', 'name')
    op.drop_column('project', 'head')
    # ### end Alembic commands ###
