"""Setup Sample Model Change Temperature Field

Revision ID: 1aa169d60117
Revises: ef7f700fc6e9
Create Date: 2019-11-13 13:08:41.074224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa169d60117'
down_revision = 'ef7f700fc6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('temperature', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_column('sample', 'temperature_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('temperature_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('sample', 'temperature')
    # ### end Alembic commands ###
