"""Added quantity type table to allow for correct labelling of sample amounts

Revision ID: 2af34b21d8e4
Revises: 177c317004ab
Create Date: 2019-12-10 12:54:51.771550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af34b21d8e4'
down_revision = '177c317004ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantity_type',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sample', sa.Column('quantity_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sample', 'quantity_type', ['quantity_type'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'quantity_type')
    op.drop_table('quantity_type')
    # ### end Alembic commands ###
