"""Added Theme Model

Revision ID: 2ea7072b7e83
Revises: 51a019aacb1a
Create Date: 2019-11-15 11:14:40.386749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea7072b7e83'
down_revision = '51a019aacb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_name'), 'theme', ['name'], unique=False)
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_theme_name'), table_name='theme')
    op.drop_table('theme')
    # ### end Alembic commands ###
