"""Unique attributes set for Tray and Rack

Revision ID: 335e9050c869
Revises: 2af34b21d8e4
Create Date: 2019-12-10 13:12:32.276338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335e9050c869'
down_revision = '2af34b21d8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rack', ['number'])
    op.create_unique_constraint(None, 'tray', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tray', type_='unique')
    op.drop_constraint(None, 'rack', type_='unique')
    # ### end Alembic commands ###
