"""Added code to Tray, Rack, Freezer and Chamber Models

Revision ID: 393b5820524d
Revises: 941c61c29c54
Create Date: 2019-11-25 15:40:45.809944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b5820524d'
down_revision = '941c61c29c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
