"""Added code to Tray, Rack, Freezer and Chamber Models

Revision ID: 393b5820524d
Revises: 941c61c29c54
Create Date: 2019-11-25 15:40:45.809944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b5820524d'
down_revision = '941c61c29c54'
branch_labels = None
depends_on = None


# todo: nullable values set to null to allow for upgrading
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rack', sa.Column('code', sa.String(length=65), nullable=True))
    op.add_column('tray', sa.Column('code', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tray', 'code')
    op.drop_column('rack', 'code')
    # ### end Alembic commands ###
