"""Relationship between sample and project explicitly defined

Revision ID: 3f45c9122778
Revises: fe5a59f28d77
Create Date: 2020-11-30 11:26:50.519972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45c9122778'
down_revision = 'fe5a59f28d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sample_project_id'), 'sample', ['project_id'], unique=False)
    op.create_index(op.f('ix_sample_slot_id'), 'sample', ['slot_id'], unique=False)
    op.create_index(op.f('ix_sample_theme_id'), 'sample', ['theme_id'], unique=False)
    op.create_index(op.f('ix_sample_user_id'), 'sample', ['user_id'], unique=False)
    op.drop_index('ix_sample_project', table_name='sample')
    op.create_foreign_key(None, 'sample', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sample', 'project_owner')
    op.drop_column('sample', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('project', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('project_owner', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.create_index('ix_sample_project', 'sample', ['project'], unique=False)
    op.drop_index(op.f('ix_sample_user_id'), table_name='sample')
    op.drop_index(op.f('ix_sample_theme_id'), table_name='sample')
    op.drop_index(op.f('ix_sample_slot_id'), table_name='sample')
    op.drop_index(op.f('ix_sample_project_id'), table_name='sample')
    op.drop_column('sample', 'project_id')
    # ### end Alembic commands ###
