"""Changed field location collected of sample to be a fk to studyblock

Revision ID: 43bfa08ae73d
Revises: 234d93c31a7c
Create Date: 2021-01-19 14:46:28.671177

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43bfa08ae73d'
down_revision = '234d93c31a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=True)
    op.add_column('sample', sa.Column('location_collected', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_sample_location_collected'), 'sample', ['location_collected'], unique=False)
    op.create_foreign_key("sample_location_collected_fkey", 'sample', 'study_block', ['location_collected'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sample_location_collected_fkey", 'sample', type_='foreignkey')
    op.drop_index(op.f('ix_sample_location_collected'), table_name='sample')
    op.drop_column('sample', 'location_collected')
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
