"""Updates on sample

Revision ID: 44fdc8ab8e6a
Revises: 0f0da4cce4ea
Create Date: 2021-01-27 17:32:10.970972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fdc8ab8e6a'
down_revision = '0f0da4cce4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('sample', 'bio_hazard_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', 'location_collected',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('sample', 'quantity_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ml'::character varying"))
    op.drop_constraint('sample_theme_id_fkey', 'sample', type_='foreignkey')
    op.drop_constraint('sample_slot_id_fkey', 'sample', type_='foreignkey')
    op.drop_constraint('sample_project_id_fkey', 'sample', type_='foreignkey')
    op.drop_constraint('sample_user_id_fkey', 'sample', type_='foreignkey')
    op.create_foreign_key(None, 'sample', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sample', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sample', 'theme', ['theme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sample', 'slot', ['slot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.create_foreign_key('sample_user_id_fkey', 'sample', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('sample_project_id_fkey', 'sample', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('sample_slot_id_fkey', 'sample', 'slot', ['slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('sample_theme_id_fkey', 'sample', 'theme', ['theme_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sample', 'quantity_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ml'::character varying"))
    op.alter_column('sample', 'location_collected',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('sample', 'bio_hazard_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
