"""date collected field of household data

Revision ID: 46881d3666e8
Revises: fa55d611d59d
Create Date: 2020-12-02 15:08:31.312157

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46881d3666e8'
down_revision = 'fa55d611d59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_health_house_data', sa.Column('date_collected', sa.DateTime(), nullable=False,
                                                        server_default='2020-09-28 11:11:05.160109'))
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('animal_health_house_data', 'date_collected')
    # ### end Alembic commands ###
