"""Changed ForeignKeys to nullable

Revision ID: 4e51c3141240
Revises: 393b5820524d
Create Date: 2019-11-26 15:29:51.911347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e51c3141240'
down_revision = '393b5820524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamber', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('freezer', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('freezer', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('chamber', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###
