"""Added Housedata Model

Revision ID: 540bf8806487
Revises: c2210b4c2bdd
Create Date: 2019-12-19 15:26:11.981032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540bf8806487'
down_revision = 'c2210b4c2bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=150), nullable=True),
    sa.Column('employment', sa.String(length=150), nullable=True),
    sa.Column('marital_status', sa.String(length=150), nullable=True),
    sa.Column('number_of_people', sa.Integer(), nullable=True),
    sa.Column('number_of_children', sa.Integer(), nullable=True),
    sa.Column('number_of_animals', sa.Integer(), nullable=True),
    sa.Column('economic_activity', sa.String(length=250), nullable=True),
    sa.Column('type_of_animals', sa.String(length=250), nullable=True),
    sa.Column('farming_activities', sa.String(length=250), nullable=True),
    sa.Column('social_economic_data', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housedata_code'), 'housedata', ['code'], unique=True)
    op.add_column('users', sa.Column('housedata_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'housedata', ['housedata_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'housedata_id')
    op.drop_index(op.f('ix_housedata_code'), table_name='housedata')
    op.drop_table('housedata')
    # ### end Alembic commands ###
