"""Setup User Model

Revision ID: 54af49545db8
Revises: e3e764c2adc7
Create Date: 2019-11-13 11:36:11.938948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54af49545db8'
down_revision = 'e3e764c2adc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=65), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.String(length=65), nullable=False),
    sa.Column('lastname', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
