"""Added code column in theme model and changed name constraint to be unique

Revision ID: 5a0b8f82953c
Revises: a469eab1034a
Create Date: 2019-11-19 11:31:13.296465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0b8f82953c'
down_revision = 'a469eab1034a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('code', sa.String(length=10), nullable=True))
    op.drop_index('ix_theme_name', table_name='theme')
    op.create_index(op.f('ix_theme_name'), 'theme', ['name'], unique=True)
    op.create_unique_constraint(None, 'theme', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theme', type_='unique')
    op.drop_index(op.f('ix_theme_name'), table_name='theme')
    op.create_index('ix_theme_name', 'theme', ['name'], unique=False)
    op.drop_column('theme', 'code')
    # ### end Alembic commands ###
