"""Added theme FK to sample.

Revision ID: 5de562f91f38
Revises: 2ea7072b7e83
Create Date: 2019-11-18 14:20:37.921631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de562f91f38'
down_revision = '2ea7072b7e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'theme', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'theme_id')
    # ### end Alembic commands ###
