"""Added_status_field_to_sample

Revision ID: 5ff467f2f7d5
Revises: 2573c8070e75
Create Date: 2020-06-19 11:30:05.070726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from api.constants import SAMPLE_FROM_FIELD

revision = '5ff467f2f7d5'
down_revision = '2573c8070e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('status', sa.String(), nullable=False, server_default=SAMPLE_FROM_FIELD))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'status')
    # ### end Alembic commands ###
