"""Adding Box, Tray, Rack, Chamber, Freezer, Laboratory Models

Revision ID: 60cdff3a515f
Revises: 1aa169d60117
Create Date: 2019-11-13 16:39:16.227917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cdff3a515f'
down_revision = '1aa169d60117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(length=65), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freezer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('freezer_number', sa.Integer(), nullable=False),
    sa.Column('room_located', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber_id', sa.Integer(), nullable=True),
    sa.Column('rack_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chamber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tray',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('tray_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tray_id', sa.Integer(), nullable=True),
    sa.Column('box_label', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['tray_id'], ['tray.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'sample', sa.Column('box_id', sa.Integer(), nullable=True))
    op.add_column(u'sample', sa.Column('retention_period', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'box', ['box_id'], ['id'])
    op.drop_column(u'sample', 'retension_period')
    op.add_column(u'users', sa.Column('first_name', sa.String(length=65), nullable=False))
    op.add_column(u'users', sa.Column('last_name', sa.String(length=65), nullable=False))
    op.add_column(u'users', sa.Column('password', sa.String(length=128), nullable=False))
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column(u'users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column(u'users', 'lastname')
    op.drop_column(u'users', 'firstname')
    op.drop_column(u'users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column(u'users', sa.Column('firstname', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.add_column(u'users', sa.Column('lastname', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.alter_column(u'users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.drop_column(u'users', 'password')
    op.drop_column(u'users', 'last_name')
    op.drop_column(u'users', 'first_name')
    op.add_column(u'sample', sa.Column('retension_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column(u'sample', 'retention_period')
    op.drop_column(u'sample', 'box_id')
    op.drop_table('box')
    op.drop_table('tray')
    op.drop_table('rack')
    op.drop_table('freezer')
    op.drop_table('laboratory')
    op.drop_table('chamber')
    # ### end Alembic commands ###
