"""Added create, update, delete time

Revision ID: 624e2763174b
Revises: 540bf8806487
Create Date: 2020-01-09 16:34:34.800212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624e2763174b'
down_revision = '540bf8806487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'updated_at')
    op.drop_column('sample', 'deleted_at')
    op.drop_column('sample', 'created_at')
    # ### end Alembic commands ###
