"""Updated sample changed relationship to slot

Revision ID: 6400953a12df
Revises: 76d63daa629d
Create Date: 2020-09-28 12:01:01.935790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6400953a12df'
down_revision = '76d63daa629d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('slot_id', sa.Integer(), nullable=True))
    op.drop_constraint('sample_box_id_fkey', 'sample', type_='foreignkey')
    op.create_foreign_key(None, 'sample', 'slot', ['slot_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sample', 'box_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('box_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.create_foreign_key('sample_box_id_fkey', 'sample', 'box', ['box_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sample', 'slot_id')
    # ### end Alembic commands ###
