"""Modifications on models to rename attributes and refine relationships.

Revision ID: 69ce815cfad9
Revises: 60cdff3a515f
Create Date: 2019-11-14 09:48:49.251662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ce815cfad9'
down_revision = '60cdff3a515f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('label', sa.String(length=65), nullable=False))
    op.drop_column('box', 'box_label')
    op.add_column('chamber', sa.Column('freezer_id', sa.Integer(), nullable=True))
    op.add_column('chamber', sa.Column('type', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'chamber', 'freezer', ['freezer_id'], ['id'])
    op.drop_column('chamber', 'chamber_type')
    op.add_column('freezer', sa.Column('freezer', sa.Integer(), nullable=False))
    op.add_column('freezer', sa.Column('room', sa.String(length=65), nullable=False))
    op.drop_column('freezer', 'freezer_number')
    op.drop_column('freezer', 'room_located')
    op.add_column('laboratory', sa.Column('name', sa.String(length=65), nullable=False))
    op.add_column('laboratory', sa.Column('room', sa.Integer(), nullable=False))
    op.drop_column('laboratory', 'lab_name')
    op.drop_column('laboratory', 'room_number')
    op.add_column('rack', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_column('rack', 'rack_number')
    op.alter_column('sample', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('sample', 'temperature',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.create_index(op.f('ix_sample_animal_species'), 'sample', ['animal_species'], unique=False)
    op.create_index(op.f('ix_sample_project'), 'sample', ['project'], unique=False)
    op.create_index(op.f('ix_sample_sample_type'), 'sample', ['sample_type'], unique=False)
    op.add_column('tray', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_column('tray', 'tray_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tray', sa.Column('tray_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tray', 'number')
    op.drop_index(op.f('ix_sample_sample_type'), table_name='sample')
    op.drop_index(op.f('ix_sample_project'), table_name='sample')
    op.drop_index(op.f('ix_sample_animal_species'), table_name='sample')
    op.alter_column('sample', 'temperature',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('sample', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('rack', sa.Column('rack_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('rack', 'number')
    op.add_column('laboratory', sa.Column('room_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('laboratory', sa.Column('lab_name', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.drop_column('laboratory', 'room')
    op.drop_column('laboratory', 'name')
    op.add_column('freezer', sa.Column('room_located', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.add_column('freezer', sa.Column('freezer_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('freezer', 'room')
    op.drop_column('freezer', 'freezer')
    op.add_column('chamber', sa.Column('chamber_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chamber', type_='foreignkey')
    op.drop_column('chamber', 'type')
    op.drop_column('chamber', 'freezer_id')
    op.add_column('box', sa.Column('box_label', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.drop_column('box', 'label')
    # ### end Alembic commands ###
