"""Sample fk fields not null

Revision ID: 6fcc5ad48cca
Revises: 43bfa08ae73d
Create Date: 2021-01-19 15:54:35.124058

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6fcc5ad48cca'
down_revision = '43bfa08ae73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=True)
    op.alter_column('sample', 'bio_hazard_level',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('sample', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('sample', 'quantity_type',
                    existing_type=sa.VARCHAR(),
                    server_default='ml', nullable=False)
    op.alter_column('sample', 'slot_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('sample', 'theme_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('sample', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sample', 'theme_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sample', 'slot_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sample', 'quantity_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('sample', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sample', 'bio_hazard_level',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
