"""Added fields to help identify reactivated accounts

Revision ID: 71d15bad42b6
Revises: ea3d5dba80de
Create Date: 2020-05-09 19:37:55.698068

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71d15bad42b6'
down_revision = 'ea3d5dba80de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reactivated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reactivated_by', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reactivated_by')
    op.drop_column('users', 'reactivated_at')
    # ### end Alembic commands ###
