"""Updated sample description column to type text

Revision ID: 76d63daa629d
Revises: d6543233e33a
Create Date: 2020-09-28 11:55:29.751876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d63daa629d'
down_revision = 'd6543233e33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'sample_description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'sample_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
