"""Additional changes to bio_hazard_level_model

Revision ID: 795f01cfeab3
Revises: f311f4b8525b
Create Date: 2020-06-05 10:46:16.181353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795f01cfeab3'
down_revision = 'f311f4b8525b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bio_hazard_level', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)

    op.drop_column('bio_hazard_level', 'description')
    op.add_column('bio_hazard_level',
                  sa.Column('description', sa.Text, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bio_hazard_level', 'description')
    op.add_column('bio_hazard_level', sa.Column('description', sa.VARCHAR(65), nullable=True))

    op.alter_column('bio_hazard_level', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###
