"""Added approved_amount field to sample_request table

Revision ID: 797dc311403e
Revises: 684d1b21992b
Create Date: 2020-06-10 14:29:33.429454

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '797dc311403e'
down_revision = '684d1b21992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_request', sa.Column('approved_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_request', 'approved_amount')
    # ### end Alembic commands ###
