"""Added Code to Sample Model

Revision ID: 798bc25aae47
Revises: 5a0b8f82953c
Create Date: 2019-11-25 12:45:11.093093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798bc25aae47'
down_revision = '5a0b8f82953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'code')
    # ### end Alembic commands ###
