"""Added Code to Sample Model

Revision ID: 798bc25aae47
Revises: 5a0b8f82953c
Create Date: 2019-11-25 12:45:11.093093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798bc25aae47'
down_revision = '5a0b8f82953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('code', sa.String(), nullable=True))
  
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.drop_column('sample', 'code')
    # ### end Alembic commands ###
