"""Renamed laboratory column to building.

Revision ID: 7fd817a34ae9
Revises: 46881d3666e8
Create Date: 2020-12-04 09:58:57.420650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd817a34ae9'
down_revision = '46881d3666e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('laboratory', sa.Column('building', sa.String(length=65), nullable=False, server_default='lab'))
    op.drop_column('laboratory', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory', sa.Column('name', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.drop_column('laboratory', 'building')
    op.alter_column('animal_health_house_data', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
