"""Added code to Chamber and Freezer Models

Revision ID: 941c61c29c54
Revises: 04007c59f87a
Create Date: 2019-11-25 15:10:44.151994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941c61c29c54'
down_revision = '04007c59f87a'
branch_labels = None
depends_on = None


# todo: nullable values set to null to allow for upgrading
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamber', sa.Column('code', sa.String(length=65), nullable=True))
    op.add_column('freezer', sa.Column('code', sa.String(length=65), nullable=True))
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.create_unique_constraint(None, 'publication', ['publication_title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publication', type_='unique')
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.drop_column('freezer', 'code')
    op.drop_column('chamber', 'code')
    # ### end Alembic commands ###
