"""Removed room field in freezer since it is redudant

Revision ID: a3d3444cccde
Revises: 7fd817a34ae9
Create Date: 2020-12-08 09:50:20.764611

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3d3444cccde'
down_revision = '7fd817a34ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=True)
    op.drop_column('freezer', 'room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freezer', sa.Column('room', sa.VARCHAR(length=65), autoincrement=False, nullable=False))
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
