"""Changed Freezer Model column

Revision ID: a469eab1034a
Revises: 5de562f91f38
Create Date: 2019-11-18 15:33:17.613479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a469eab1034a'
down_revision = '5de562f91f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freezer', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_column('freezer', 'freezer')
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('freezer', sa.Column('freezer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('freezer', 'number')
    # ### end Alembic commands ###
