"""Added Extra fields for deactivating user account

Revision ID: a5b79aea0c5a
Revises: 5d0e9b3e85d0
Create Date: 2020-05-07 15:57:32.238536

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a5b79aea0c5a'
down_revision = '5d0e9b3e85d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deactivated_by', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_by')
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
