"""Changed field location collected of sample to be a fk to studyblock

Revision ID: b007a3888ebb
Revises: 18d9a31dd9ce
Create Date: 2021-01-19 14:01:14.665195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b007a3888ebb'
down_revision = '18d9a31dd9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=True)
    op.execute('ALTER TABLE sample ALTER COLUMN location_collected TYPE integer USING(location_collected::integer);')
    op.alter_column('sample', 'location_collected',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.create_index(op.f('ix_sample_location_collected'), 'sample', ['location_collected'], unique=False)
    op.create_foreign_key(None, 'sample', 'study_block', ['location_collected'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_index(op.f('ix_sample_location_collected'), table_name='sample')
    op.alter_column('sample', 'location_collected',
                    existing_type=sa.Integer(),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('animal_health_house_data', 'weight',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    # ### end Alembic commands ###
