"""Study block relationship with house hold data.

Revision ID: b78f11e57b5b
Revises: 40f6db64fc74
Create Date: 2020-11-26 10:21:48.140462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78f11e57b5b'
down_revision = '40f6db64fc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_health_house_data', sa.Column('study_block_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'animal_health_house_data', 'study_block', ['study_block_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal_health_house_data', type_='foreignkey')
    op.drop_column('animal_health_house_data', 'study_block_id')
    # ### end Alembic commands ###
