"""Added deleted_by column to sample

Revision ID: ba2b5728d0c3
Revises: 624e2763174b
Create Date: 2020-01-10 11:23:35.796684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2b5728d0c3'
down_revision = '624e2763174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('deleted_by', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'deleted_by')
    # ### end Alembic commands ###
