"""Renamed field cc_ml to cc.

Revision ID: c1be6963f46d
Revises: 165cf1d7d1d4
Create Date: 2020-11-25 14:30:51.841923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1be6963f46d'
down_revision = '165cf1d7d1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_health_house_data', sa.Column('cc', sa.String(), nullable=True))
    op.drop_column('animal_health_house_data', 'cc_ml')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_health_house_data', sa.Column('cc_ml', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('animal_health_house_data', 'cc')
    # ### end Alembic commands ###
