"""Updated rack model made code unique and created an index on it.

Revision ID: c54130e1a1f1
Revises: 06570f5559c8
Create Date: 2020-02-18 15:53:19.174783

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c54130e1a1f1'
down_revision = '06570f5559c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'publication_title',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=False)
    op.create_index(op.f('ix_rack_code'), 'rack', ['code'], unique=True)
    op.drop_constraint('rack_number_key', 'rack', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rack_number_key', 'rack', ['number'])
    op.drop_index(op.f('ix_rack_code'), table_name='rack')
    op.alter_column('publication', 'publication_title',
                    existing_type=sa.VARCHAR(length=150),
                    nullable=True)
    # ### end Alembic commands ###
