"""On delete box, delete all slots associated with the box.

Revision ID: e4d413c34c1b
Revises: 73f9752b5d49
Create Date: 2020-12-15 12:05:13.935524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d413c34c1b'
down_revision = '73f9752b5d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slot_box_id_fkey', 'slot', type_='foreignkey')
    op.create_foreign_key(None, 'slot', 'box', ['box_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.create_foreign_key('slot_box_id_fkey', 'slot', 'box', ['box_id'], ['id'])
    # ### end Alembic commands ###
