"""Password reset field added to schema

Revision ID: ea3d5dba80de
Revises: a5b79aea0c5a
Create Date: 2020-05-09 17:41:13.144841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea3d5dba80de'
down_revision = 'a5b79aea0c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_on')
    # ### end Alembic commands ###
