"""Rename of SecurityLevel to BioHazardLevel

Revision ID: f311f4b8525b
Revises: 192f2be30501
Create Date: 2020-06-05 09:41:16.217710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f311f4b8525b'
down_revision = '192f2be30501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_hazard_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=65), nullable=True),
    sa.Column('name', sa.String(length=65), nullable=True),
    sa.Column('description', sa.String(length=65), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('sample_security_level_fkey', 'sample', type_='foreignkey')
    op.drop_table('security_level')
    op.add_column('sample', sa.Column('bio_hazard_level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'bio_hazard_level', ['bio_hazard_level'], ['id'], ondelete='SET NULL')
    op.drop_column('sample', 'security_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('security_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.create_foreign_key('sample_security_level_fkey', 'sample', 'security_level', ['security_level'], ['id'], ondelete='SET NULL')
    op.drop_column('sample', 'bio_hazard_level')
    op.create_table('security_level',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_level_pkey')
    )
    op.drop_table('bio_hazard_level')
    # ### end Alembic commands ###
