"""Changes to user model, made role and created_by field not null

Revision ID: f5aff887f40a
Revises: ba2b5728d0c3
Create Date: 2020-01-31 15:33:51.946430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aff887f40a'
down_revision = 'ba2b5728d0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###
