"""Updated constraints on user

Revision ID: fab4f09b2f75
Revises: d1c7392d5540
Create Date: 2019-11-26 13:46:00.385550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fab4f09b2f75'
down_revision = 'd1c7392d5540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamber', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('freezer', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tray', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('rack', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('laboratory', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('freezer', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('chamber', 'code',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###
