"""Area of study block not unique.

Revision ID: fe5a59f28d77
Revises: b78f11e57b5b
Create Date: 2020-11-26 11:25:31.895931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5a59f28d77'
down_revision = 'b78f11e57b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_block_area_key', 'study_block', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('study_block_area_key', 'study_block', ['area'])
    # ### end Alembic commands ###
